vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
-- vim.cmd("set number")
-- vim.cmd("set relativenumber")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set smartindent")
vim.cmd("set autoindent")
vim.cmd("set signcolumn=auto")
vim.cmd("set laststatus=0")
vim.opt.fillchars = { vert = "|", eob = " " }
